const DummyEnrolrolmentData = [
  {
    slNo: "1",
    name: "when do we eat",
    type: "club",
    address: "225 Rugby Road,Gloucester,Wyoming,1725",
    email: "abc123@gmail.com",
    created: "May11,2014",
    action: "Location",
  },
  {
    slNo: "2",
    name: "when do we eat",
    type: "club",
    address: "225 Rugby Road,Gloucester,Wyoming,1725",
    email: "abc123@gmail.com",
    created: "May11,2014",
    action: "Location",
  },
  {
    slNo: "3",
    name: "when do we eat",
    type: "club",
    address: "225 Rugby Road,Gloucester,Wyoming,1725",
    email: "abc123@gmail.com",
    created: "May11,2014",
    action: "Location",
  },
  {
    slNo: "4",
    name: "when do we eat",
    type: "club",
    address: "225 Rugby Road,Gloucester,Wyoming,1725",
    email: "abc123@gmail.com",
    created: "May11,2014",
    action: "Location",
  },
  {
    slNo: "5",
    name: "when do we eat",
    type: "club",
    address: "225 Rugby Road,Gloucester,Wyoming,1725",
    email: "abc123@gmail.com",
    created: "May11,2014",
    action: "Location",
  },
  {
    slNo: "6",
    name: "when do we eat",
    type: "club",
    address: "225 Rugby Road,Gloucester,Wyoming,1725",
    email: "abc123@gmail.com",
    created: "May11,2014",
    action: "Location",
  },
  {
    slNo: "7",
    name: "when do we eat",
    type: "club",
    address: "225 Rugby Road,Gloucester,Wyoming,1725",
    email: "abc123@gmail.com",
    created: "May11,2014",
    action: "Location",
  },
  {
    slNo: "8",
    name: "when do we eat",
    type: "club",
    address: "225 Rugby Road,Gloucester,Wyoming,1725",
    email: "abc123@gmail.com",
    created: "May11,2014",
    action: "Location",
  },
  {
    slNo: "9",
    name: "when do we eat",
    type: "club",
    address: "225 Rugby Road,Gloucester,Wyoming,1725",
    email: "abc123@gmail.com",
    created: "May11,2014",
    action: "Location",
  },
  {
    slNo: "10",
    name: "when do we eat",
    type: "club",
    address: "225 Rugby Road,Gloucester,Wyoming,1725",
    email: "abc123@gmail.com",
    created: "May11,2014",
    action: "Location",
  },
  {
    slNo: "11",
    name: "when do we eat",
    type: "club",
    address: "225 Rugby Road,Gloucester,Wyoming,1725",
    email: "abc123@gmail.com",
    created: "May11,2014",
    action: "Location",
  },
  {
    slNo: "12",
    name: "when do we eat",
    type: "club",
    address: "225 Rugby Road,Gloucester,Wyoming,1725",
    email: "abc123@gmail.com",
    created: "May11,2014",
    action: "Location",
  },
  {
    slNo: "13",
    name: "when do we eat",
    type: "club",
    address: "225 Rugby Road,Gloucester,Wyoming,1725",
    email: "abc123@gmail.com",
    created: "May11,2014",
    action: "Location",
  },
  {
    slNo: "14",
    name: "when do we eat",
    type: "club",
    address: "225 Rugby Road,Gloucester,Wyoming,1725",
    email: "abc123@gmail.com",
    created: "May11,2014",
    action: "Location",
  },

  {
    slNo: "15",
    name: "when do we eat",
    type: "club",
    address: "225 Rugby Road,Gloucester,Wyoming,1725",
    email: "abc123@gmail.com",
    created: "May11,2014",
    action: "Location",
  },
  {
    slNo: "16",
    name: "when do we eat",
    type: "club",
    address: "225 Rugby Road,Gloucester,Wyoming,1725",
    email: "abc123@gmail.com",
    created: "May11,2014",
    action: "Location",
  },
  {
    slNo: "17",
    name: "when do we eat",
    type: "club",
    address: "225 Rugby Road,Gloucester,Wyoming,1725",
    email: "abc123@gmail.com",
    created: "May11,2014",
    action: "Location",
  },
  {
    slNo: "18",
    name: "when do we eat",
    type: "club",
    address: "225 Rugby Road,Gloucester,Wyoming,1725",
    email: "abc123@gmail.com",
    created: "May11,2014",
    action: "Location",
  },
  {
    slNo: "19",
    name: "when do we eat",
    type: "club",
    address: "225 Rugby Road,Gloucester,Wyoming,1725",
    email: "abc123@gmail.com",
    created: "May11,2014",
    action: "Location",
  },
  {
    slNo: "20",
    name: "when do we eat",
    type: "club",
    address: "225 Rugby Road,Gloucester,Wyoming,1725",
    email: "abc123@gmail.com",
    created: "May11,2014",
    action: "Location",
  },

  {
    slNo: "21",
    name: "when do we eat",
    type: "club",
    address: "225 Rugby Road,Gloucester,Wyoming,1725",
    email: "abc123@gmail.com",
    created: "May11,2014",
    action: "Location",
  },
  {
    slNo: "22",
    name: "when do we eat",
    type: "club",
    address: "225 Rugby Road,Gloucester,Wyoming,1725",
    email: "abc123@gmail.com",
    created: "May11,2014",
    action: "Location",
  },
  {
    slNo: "23",
    name: "when do we eat",
    type: "club",
    address: "225 Rugby Road,Gloucester,Wyoming,1725",
    email: "abc123@gmail.com",
    created: "May11,2014",
    action: "Location",
  },
  {
    slNo: "24",
    name: "when do we eat",
    type: "club",
    address: "225 Rugby Road,Gloucester,Wyoming,1725",
    email: "abc123@gmail.com",
    created: "May11,2014",
    action: "Location",
  },
  {
    slNo: "25",
    name: "when do we eat",
    type: "club",
    address: "225 Rugby Road,Gloucester,Wyoming,1725",
    email: "abc123@gmail.com",
    created: "May11,2014",
    action: "Location",
  },
];

export default DummyEnrolrolmentData;
