const DummyData = [
  {
    username: "chotu",
    name: "Chotachetan",
    lastlocation: "Ghar",
    visits: "100",
    followers: "10000",
    following: "200",
    created: " July 22,2021",
    status: " Active",
    action: " Block | View ",
  },
  {
    username: "chotu",
    name: "Chotachetan",
    lastlocation: "Ghar",
    visits: "100",
    followers: "10000",
    following: "200",
    created: " July 22,2021",
    status: " Active",
    action: " Block | View ",
  },
  {
    username: "chotu",
    name: "Chotachetan",
    lastlocation: "Ghar",
    visits: "100",
    followers: "10000",
    following: "200",
    created: " July 22,2021",
    status: " Active",
    action: " Block | View ",
  },
  {
    username: "chotu",
    name: "Chotachetan",
    lastlocation: "Ghar",
    visits: "100",
    followers: "10000",
    following: "200",
    created: " July 22,2021",
    status: " Active",
    action: " Block | View ",
  },
  {
    username: "chotu",
    name: "Chotachetan",
    lastlocation: "Ghar",
    visits: "100",
    followers: "10000",
    following: "200",
    created: " July 22,2021",
    status: " Active",
    action: " Block | View ",
  },
  {
    username: "chotu",
    name: "Chotachetan",
    lastlocation: "Ghar",
    visits: "100",
    followers: "10000",
    following: "200",
    created: " July 22,2021",
    status: " Active",
    action: " Block | View ",
  },
  {
    username: "chotu",
    name: "Chotachetan",
    lastlocation: "Ghar",
    visits: "100",
    followers: "10000",
    following: "200",
    created: " July 22,2021",
    status: " Active",
    action: " Block | View ",
  },
  {
    username: "chotu",
    name: "Chotachetan",
    lastlocation: "Ghar",
    visits: "100",
    followers: "10000",
    following: "200",
    created: " July 22,2021",
    status: " Active",
    action: " Block | View ",
  },
  {
    username: "chotu",
    name: "Chotachetan",
    lastlocation: "Ghar",
    visits: "100",
    followers: "10000",
    following: "200",
    created: " July 22,2021",
    status: " Active",
    action: " Block | View ",
  },
  {
    username: "chotu",
    name: "Chotachetan",
    lastlocation: "Ghar",
    visits: "100",
    followers: "10000",
    following: "200",
    created: " July 22,2021",
    status: " Active",
    action: " Block | View ",
  },
  {
    username: "chotu",
    name: "Chotachetan",
    lastlocation: "Ghar",
    visits: "100",
    followers: "10000",
    following: "200",
    created: " July 22,2021",
    status: " Active",
    action: " Block | View ",
  },
  {
    username: "chotu",
    name: "Chotachetan",
    lastlocation: "Ghar",
    visits: "100",
    followers: "10000",
    following: "200",
    created: " July 22,2021",
    status: " Active",
    action: " Block | View ",
  },
  {
    username: "chotu",
    name: "Chotachetan",
    lastlocation: "Ghar",
    visits: "100",
    followers: "10000",
    following: "200",
    created: " July 22,2021",
    status: " Active",
    action: " Block | View ",
  },
  {
    username: "chotu",
    name: "Chotachetan",
    lastlocation: "Ghar",
    visits: "100",
    followers: "10000",
    following: "200",
    created: " July 22,2021",
    status: " Active",
    action: " Block | View ",
  },
  {
    username: "chotu",
    name: "Chotachetan",
    lastlocation: "Ghar",
    visits: "100",
    followers: "10000",
    following: "200",
    created: " July 22,2021",
    status: " Active",
    action: " Block | View ",
  },
  {
    username: "chotu",
    name: "Chotachetan",
    lastlocation: "Ghar",
    visits: "100",
    followers: "10000",
    following: "200",
    created: " July 22,2021",
    status: " Active",
    action: " Block | View ",
  },
  {
    username: "chotu",
    name: "Chotachetan",
    lastlocation: "Ghar",
    visits: "100",
    followers: "10000",
    following: "200",
    created: " July 22,2021",
    status: " Active",
    action: " Block | View ",
  },
  {
    username: "chotu",
    name: "Chotachetan",
    lastlocation: "Ghar",
    visits: "100",
    followers: "10000",
    following: "200",
    created: " July 22,2021",
    status: " Active",
    action: " Block | View ",
  },
  {
    username: "chotu",
    name: "Chotachetan",
    lastlocation: "Ghar",
    visits: "100",
    followers: "10000",
    following: "200",
    created: " July 22,2021",
    status: " Active",
    action: " Block | View ",
  },
  {
    username: "chotu",
    name: "Chotachetan",
    lastlocation: "Ghar",
    visits: "100",
    followers: "10000",
    following: "200",
    created: " July 22,2021",
    status: " Active",
    action: " Block | View ",
  },
  {
    username: "chotu",
    name: "Chotachetan",
    lastlocation: "Ghar",
    visits: "100",
    followers: "10000",
    following: "200",
    created: " July 22,2021",
    status: " Active",
    action: " Block | View ",
  },
  {
    username: "chotu",
    name: "Chotachetan",
    lastlocation: "Ghar",
    visits: "100",
    followers: "10000",
    following: "200",
    created: " July 22,2021",
    status: " Active",
    action: " Block | View ",
  },
];

export default DummyData;
