const DummyAdminData = [
  {
    slNo: "1",
    name: "when do we eat",
    email: "abc123@gmail.com",
    created: "May11,2014",
    permission: "Places,Users,Settings",
    status: "Active",
    action: "Location",
  },
  {
    slNo: "2",
    name: "when do we eat",
    email: "abc123@gmail.com",
    created: "May11,2014",
    permission: "Places,Users,Settings",
    status: "Active",
    action: "Location",
  },
  {
    slNo: "3",
    name: "when do we eat",
    email: "abc123@gmail.com",
    created: "May11,2014",
    permission: "Places,Users,Settings",
    status: "Active",
    action: "Location",
  },
  {
    slNo: "4",
    name: "when do we eat",
    email: "abc123@gmail.com",
    created: "May11,2014",
    permission: "Places,Users,Settings",
    status: "Active",
    action: "Location",
  },
  {
    slNo: "5",
    name: "when do we eat",
    email: "abc123@gmail.com",
    created: "May11,2014",
    permission: "Places,Users,Settings",
    status: "Active",
    action: "Location",
  },
  {
    slNo: "6",
    name: "when do we eat",
    email: "abc123@gmail.com",
    created: "May11,2014",
    permission: "Places,Users,Settings",
    status: "Active",
    action: "Location",
  },
  {
    slNo: "7",
    name: "when do we eat",
    email: "abc123@gmail.com",
    created: "May11,2014",
    permission: "Places,Users,Settings",
    status: "Active",
    action: "Location",
  },
  {
    slNo: "1",
    name: "when do we eat",
    email: "abc123@gmail.com",
    created: "May11,2014",
    permission: "Places,Users,Settings",
    status: "Active",
    action: "Location",
  },
  {
    slNo: "1",
    name: "when do we eat",
    email: "abc123@gmail.com",
    created: "May11,2014",
    permission: "Places,Users,Settings",
    status: "Active",
    action: "Location",
  },
  {
    slNo: "1",
    name: "when do we eat",
    email: "abc123@gmail.com",
    created: "May11,2014",
    permission: "Places,Users,Settings",
    status: "Active",
    action: "Location",
  },
  {
    slNo: "1",
    name: "when do we eat",
    email: "abc123@gmail.com",
    created: "May11,2014",
    permission: "Places,Users,Settings",
    status: "Active",
    action: "Location",
  },
  {
    slNo: "1",
    name: "when do we eat",
    email: "abc123@gmail.com",
    created: "May11,2014",
    permission: "Places,Users,Settings",
    status: "Active",
    action: "Location",
  },
  {
    slNo: "1",
    name: "when do we eat",
    email: "abc123@gmail.com",
    created: "May11,2014",
    permission: "Places,Users,Settings",
    status: "Active",
    action: "Location",
  },
  {
    slNo: "1",
    name: "when do we eat",
    email: "abc123@gmail.com",
    created: "May11,2014",
    permission: "Places,Users,Settings",
    status: "Active",
    action: "Location",
  },
  {
    slNo: "1",
    name: "when do we eat",
    email: "abc123@gmail.com",
    created: "May11,2014",
    permission: "Places,Users,Settings",
    status: "Active",
    action: "Location",
  },
  {
    slNo: "1",
    name: "when do we eat",
    email: "abc123@gmail.com",
    created: "May11,2014",
    permission: "Places,Users,Settings",
    status: "Active",
    action: "Location",
  },
  {
    slNo: "1",
    name: "when do we eat",
    email: "abc123@gmail.com",
    created: "May11,2014",
    permission: "Places,Users,Settings",
    status: "Active",
    action: "Location",
  },
  {
    slNo: "1",
    name: "when do we eat",
    email: "abc123@gmail.com",
    created: "May11,2014",
    permission: "Places,Users,Settings",
    status: "Active",
    action: "Location",
  },
  {
    slNo: "1",
    name: "when do we eat",
    email: "abc123@gmail.com",
    created: "May11,2014",
    permission: "Places,Users,Settings",
    status: "Active",
    action: "Location",
  },
  {
    slNo: "1",
    name: "when do we eat",
    email: "abc123@gmail.com",
    created: "May11,2014",
    permission: "Places,Users,Settings",
    status: "Active",
    action: "Location",
  },
  {
    slNo: "1",
    name: "when do we eat",
    email: "abc123@gmail.com",
    created: "May11,2014",
    permission: "Places,Users,Settings",
    status: "Active",
    action: "Location",
  },
  {
    slNo: "1",
    name: "when do we eat",
    email: "abc123@gmail.com",
    created: "May11,2014",
    permission: "Places,Users,Settings",
    status: "Active",
    action: "Location",
  },
  {
    slNo: "23",
    name: "when do we eat",
    email: "abc123@gmail.com",
    created: "May11,2014",
    permission: "Places,Users,Settings",
    status: "Active",
    action: "Location",
  },
  {
    slNo: "24",
    name: "when do we eat",
    email: "abc123@gmail.com",
    created: "May11,2014",
    permission: "Places,Users,Settings",
    status: "Active",
    action: "Location",
  },
  {
    slNo: "25",
    name: "when do we eat",
    email: "abc123@gmail.com",
    created: "May11,2014",
    permission: "Places,Users,Settings",
    status: "Active",
    action: "Location",
  },
];

export default DummyAdminData;
